name = "MarketBigPictureWatch"
uuid = "ff0c1feb-3a7b-4803-83b1-b83ce1784aa3"
authors = ["Zhong Pan <zhopan77@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
MarketData = "945b72a4-3b13-509d-9b46-1525bb5c06de"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
QuandlAccess = "9828b13b-9cf9-4ed3-a262-66ff2e7f23f2"
SortingAlgorithms = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
